M48
; DRILL file {KiCad 9.0.0} date 2025-04-28T18:40:01+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-28T18:40:01+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.889
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.020
%
G90
G05
T1
X152.547Y-121.1
X152.547Y-123.4
T2
X127.75Y-102.15
X134.25Y-102.15
M30
